config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  resources :tasks, except: :show do
    resources :task_items
  end
  resources :patients do
    resources :task_assignments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  acts_as_paranoid
  self.abstract_class = true
end

app/models/patient.rb
class Patient < ApplicationRecord
  has_many :task_assignments, dependent: :destroy
  has_many :tasks, through: :task_assignments, dependent: :destroy
  has_many :task_items, through: :task_assignments, dependent: :destroy

  validates :first_name, :last_name, presence: true
  validates_format_of :first_name, :last_name, :with => /\A[A-Za-z]*$\z/, multiline: false
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :task_items, dependent: :destroy
  has_many :task_assignments, dependent: :destroy
  has_many :patients, class_name: 'Patient', through: :task_assignments,
           foreign_key: :patient_id, dependent: :destroy

  validates :task_name, presence: true
end

app/models/task_assignment.rb
class TaskAssignment < ApplicationRecord
  belongs_to :patient
  belongs_to :task
  belongs_to :task_item

  validates :task_id, :patient_id, :due_date, presence: true
  validates_date :due_date, on_or_after: -> { Date.current }

  default_scope { order(due_date: :desc) }
end

app/models/task_item.rb
class TaskItem < ApplicationRecord
  belongs_to :task
  has_many :task_assignments, dependent: :destroy
  has_many :patients, class_name: 'Patient',
                      through: :task_assignments, foreign_key: :task_id,
                      dependent: :destroy, source: :task

  validates :title, :body, :due_days, presence: true
  validates :due_days, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates_length_of :title, minimum: 5, maximum: 100
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[show edit update destroy]

  def index
    @patients = Patient.includes(:task_assignments, :task_items).all
  end

  def show; end

  def new
    @patient = Patient.new
  end

  def edit; end

  def create
    @patient = Patient.new(patient_params)
    if @patient.save
      redirect_to patients_path, notice: t('.index.messages.success_create')
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @patient.update(patient_params)
      redirect_to @patient, notice: t('.index.messages.success_update')
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @patient.destroy
    redirect_to patients_url, notice: t('.index.messages.success_destroy')
  end

  private

  def set_patient
    @patient = Patient.find(params[:id])
  end

  def patient_params
    params.require(:patient).permit(:first_name, :last_name)
  end
end

app/controllers/task_assignments_controller.rb
# frozen_string_literal: true

class TaskAssignmentsController < ApplicationController
  before_action :set_patient
  before_action :set_task_assignment, only: %i[show edit update destroy]

  def index
    @task_assignments = @patient.task_assignments.all
  end

  def show; end

  def new
    @all_tasks = Task.includes(:task_items).all
    @task_assignment = @patient.task_assignments.new
  end

  def edit; end

  def create
    params.dig(:task_assignment, :task_item_ids)
          .reject(&:empty?)
          .each do |item_id|
            @patient.task_assignments.new(
                task_assignment_params.merge({task_item_id: item_id.to_i})
            )
          end

    if @patient.save
      return redirect_to patients_path,
                         notice: t('.index.messages.success_create')
    end

    @all_tasks = Task.includes(:task_items).all
    render :new, status: :unprocessable_entity
  end

  def update
    if @task_assignment.update(task_assignment_params)
      return redirect_to patient_task_assignments_path(@patient),
                         notice: t('.index.messages.success_update')
    end

    render :edit, status: :unprocessable_entity
  end

  def destroy
    @task_assignment.destroy
    redirect_to task_assignments_path,
                notice: t('.index.messages.success_destroy')
  end

  private

  def set_patient
    @patient = Patient.find_by_id(params[:patient_id])
  end

  def set_task_assignment
    @task_assignment = TaskAssignment.find(params[:id])
  end

  def task_assignment_params
    params.require(:task_assignment).permit(:patient_id, :task_id, :due_date, :is_completed)
  end
end

app/controllers/task_items_controller.rb
# frozen_string_literal: true

class TaskItemsController < ApplicationController
  before_action :set_task
  before_action :set_task_item, except: :index

  def index
    @task_items = @task.task_items.all
  end

  def show; end

  def edit; end

  def create
    @task_item = @task.task_items.new(task_item_params)
    if @task_item.save
      return redirect_to task_task_items_path(@task),
                         notice: t('.index.messages.success_create')
    end

    render :new, status: :unprocessable_entity
  end

  def update
    if @task_item.update(task_item_params)
      return redirect_to @task_item,
                         notice: t('.index.messages.success_update')
    end

    render :edit, status: :unprocessable_entity
  end

  def destroy
    @task_item.destroy
    redirect_to task_task_items_url,
                notice: t('.index.messages.success_destroy')
  end

  private

  def set_task
    @task = Task.find(params[:task_id])
  end

  def set_task_item
    @task_item = TaskItem.find_by_id(params[:id]) || @task.task_items.new
  end

  def task_item_params
    params.require(:task_item).permit(%i[title body due_days task_references])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[edit update destroy]

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def edit; end

  def create
    @task = Task.new(task_params)
    return redirect_to tasks_path, notice: t('.index.messages.success_create') if @task.save

    render :new, status: :unprocessable_entity
  end

  def update
    return redirect_to @task, notice: t('.index.messages.success_update') if @task.update(task_params)

    render :edit, status: :unprocessable_entity
  end

  def destroy
    @task.destroy
    redirect_to tasks_url, notice: t('.index.messages.success_destroy')
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:task_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Wellbe
    %meta{:content => "width=device-width,initial-scale=1", :name => "viewport"}/
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = favicon_link_tag asset_path('fav.png')
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    %nav.navbar.navbar-expand-lg
      #custom-container.container
        %a.navbar-brand
          %img(src="#{asset_path('logo.png')}")
        %ul.navbar-nav
          %li.nav-item
            %a.nav-link#pill{href: tasks_path } Tasks
          %li.nav-item
            %a.nav-link#pill{href: patients_path} Patients

    = yield

app/views/patients/_form.html.haml
#todo.py-5
  .container
    .img-content-wrapper
      %img.img-fluid.rounded{:alt => "", :src => "#{asset_path('img-holder.png')}"}/
      %h4.dashboard-title
        %a{:href => "#"} Add Patient
    #add-todo
      = form_with(model: patient) do |form|
        - if patient.errors.any?
          #error_explanation
            %h2
              = pluralize(patient.errors.count, "error")
              prohibited this patient from being saved:
            %ul
              - patient.errors.each do |error|
                %li= error.full_message
        .form-group
          = form.text_field :first_name, class:'form-control', placeholder: 'Enter First Name'
        .form-group.mt-2
          = form.text_field :last_name, class:'form-control', placeholder: 'Last  Name'
        #action-buttons.text-center.mt-4
          = link_to 'CANCEL', patients_path, class: 'btn  btn-edit btn-general'
          = form.submit class: 'btn  btn-edit btn-general'

app/views/patients/edit.html.haml
%h1 Editing Patient
= render 'form', patient: @patient
= link_to 'Show', @patient
|
= link_to 'Back', patients_path

app/views/patients/index.html.haml
%p#notice= notice
#dashboard
  .container
    .row.mb-4
      .col-md-10
        %h2 Tasks
      .col-md-2.text-right
        = link_to 'Add Patient',new_patient_path, class: 'btn  btn-success text-white ml-1'

    #todo-wrapper
      - @patients.each do |patient|
        .row.mb-1.data-row
          .col-md-6.ml-1
            = "#{patient.first_name} #{patient.last_name}"
          .col-md-3.ml-1
            = patient.created_at.strftime("%e %b, %Y")
          .col-md-3.text-right
            - if patient.task_assignments.any?
              = link_to 'View', patient_task_assignments_path(patient), class: 'btn btn-primary'
            - else
              = link_to 'Assign', new_patient_task_assignment_path(patient), class: 'btn btn-primary'
            = link_to 'Edit', edit_patient_path(patient), class: 'btn btn-primary btn-edit', role: :button
            = link_to 'Destroy', patient, method: :delete, data: {confirm: 'Are you sure?'}, class: 'btn btn-delete'

app/views/patients/new.html.haml
= render 'form', patient: @patient

app/views/patients/show.html.haml
%p#notice= notice
%p
  %strong First name:
  = @patient.first_name
%p
  %strong Last name:
  = @patient.last_name
= link_to 'Edit', edit_patient_path(@patient)
|
= link_to 'Back', patients_path

app/views/task_assignments/_form.html.haml
= form_with(model: task_assignment, url: [@patient, @task_assignment]) do |form|
  - if @patient.errors.any?
    #error_explanation
      %h2
        = pluralize(@patient.errors.count, "error")
        prohibited this task_assignment from being saved:
      %ul
        - @patient.errors.each do |error|
          %li= error.full_message
  #todo
    .container
      .img-content-wrapper
        %img.img-fluid.rounded{:alt => "", :src => "#{asset_path('img-holder.png')}"}/
        %h4.dashboard-title
          %a{:href => "#"} Create Patient Assignment
      #add-todo
        .form-group.mt-4
          = form.select :task_id,  Task.all.collect {|p| [ p.task_name, p.id ] },{} ,class: 'form-control'
        .form-group.row.mt-4
          .col-12
            = form.date_select :due_date, {},class: 'form-control'
        .form-group.mt-4
          = form.select(:task_item_ids, @all_tasks&.first&.task_items&.all&.collect {|p| [ p.title, p.id ] }, {}, |
            { :multiple => true, :size => 5, allow_null: false, class: 'form-select'  })                         |
        #action-buttons.text-center.mt-4
          = link_to 'CANCEL', patients_path, class: 'btn  btn-edit btn-general'
          = form.submit class: 'btn  btn-edit btn-general'

app/views/task_assignments/edit.html.haml
%h1 Editing Task Assignment
= render 'form', task_assignment: @task_assignment
= link_to 'Show', patient_task_assignment_path(@patient,@task_assignment)
|
= link_to 'Back', patient_task_assignments_path

app/views/task_assignments/index.html.haml
%p#notice= notice
- if @patient.task_assignments.collect(&:is_completed).all?
  .alert.alert-success
    All Task Items Completed
.card
  .card-header
    %h1.card-title= "#{@patient.first_name} #{@patient.last_name}"
    %p= @task_assignments.first&.task&.task_name
  .card-body.m-5
    - @task_assignments.each do |task_assignment|
      .accordion.accordion-flush{:id => "accordionFlushExample-#{task_assignment.id}"}
        .accordion-item
          %h2.accordion-header{:id => "flush-headingOne-#{task_assignment.id}"}
            %button.accordion-button.collapsed{"aria-controls" => "flush-collapseOne", "aria-expanded" => "false", "data-bs-target" => "#flush-collapseOne-#{task_assignment.id}", "data-bs-toggle" => "collapse", :type => "button"}
              %span.ml-2.mr-4
                = link_to patient_task_assignment_path(@patient, task_assignment, {task_assignment: {is_completed: !task_assignment.is_completed}}), method: :put, class: 'remote-link' do
                  %i{:class => "fa fa-check grey #{task_assignment.is_completed ? 'completed' : 'pending'}"}
              .modal-title.m-2.pl-2
                = task_assignment.task_item.title
                - if Date.today > task_assignment.due_date + task_assignment.task_item.due_days.to_i.days
                  %i.fa.fa-exclamation-triangle
                - else
                  %span.badge.bg-success
                    start date: #{task_assignment.due_date}

          .accordion-collapse.collapse{"aria-labelledby" => "flush-headingOne-#{task_assignment.id}", "data-bs-parent" => "#accordionFlushExample-#{task_assignment.id}", :id => "flush-collapseOne-#{task_assignment.id}"}
            .accordion-body
              = task_assignment.task_item.body.html_safe

app/views/task_assignments/new.html.haml
= render 'form', task_assignment: @task_assignment

:javascript
  let task_items = "#{@all_tasks.to_json(only: [:id, :task_name],include: {task_items: {only: [:id, :title]} })}".replace(/&quot;/g, '"');
  task_items = JSON.parse(task_items)
  console.log(task_items);

app/views/task_assignments/show.html.haml
%p#notice= notice
%p
  %strong Patient:
  = @task_assignment.patient.first_name
%p
  %strong Task:
  = @task_assignment.task.task_name
%p
  %strong Task item:
  = @task_assignment.task_item.title
%p
  %strong Due date:
  = @task_assignment.due_date
%p
  %strong Is completed:
  = @task_assignment.is_completed
= link_to 'Edit', edit_patient_task_assignment_path(@task_assignment)
|
= link_to 'Back', patient_task_assignments_path

app/views/task_items/_form.html.haml
#todo
  .container
    .img-content-wrapper.task_item
      %img.img-fluid.rounded{:alt => "", :src => "#{asset_path('img-holder.png')}"}/
      %h4.dashboard-title
        %a{:href => "#"} Add Task Item
    %div{:id => "add-todo m-0"}
      = form_with(model: task_item, url: [@task, @task_item]) do |form|
        - if task_item.errors.any?
          #error_explanation
            %h2
              = pluralize(task_item.errors.count, "error")
              prohibited this task_item from being saved:
            %ul
              - task_item.errors.each do |error|
                %li= error.full_message
        .form-group
          = form.text_field :title,class: 'form-control', placeholder: 'Title'
        .form-group.mt-3
          = form.text_area :body, :class => "tinymce", :rows => 10, :cols => 50
        .form-group.mt-3
          = form.number_field :due_days, class: 'form-control', placeholder: 'Due Days'
        #action-buttons.text-center.mt-4
          = link_to 'CANCEL', task_task_items_path, class: 'btn  btn-edit btn-general'
          = form.submit class: 'btn  btn-edit btn-general'

app/views/task_items/edit.html.haml
%h1 Editing Task Item
= render 'form', task_item: @task_item
= link_to 'Show', edit_task_task_item_path(@task, @task_item)
|
= link_to 'Back', task_task_items_path(@task)

app/views/task_items/index.html.haml
%p#notice= notice
%div{:id => "dashboard task-dashboard"}
  .container
    .row.mb-4
      .col-md-10
        %h2 Task Items
      .col-md-2.text-right
        = link_to 'Add Task Item',new_task_task_item_path, class: 'btn btn-success text-white ml-1'

    #todo-wrapper
      - @task_items.each do |task_item|
        .row.mb-1.data-row
          .col-md-6.ml-1
            = task_item.title
          .col-md-3.ml-1
            %span.badge.bg-success
              due days: #{task_item.due_days}
          .col-md-3.text-right
            = link_to 'Edit', edit_task_task_item_path(@task,task_item) , class: 'btn btn-primary', role: :button
            = link_to 'Destroy', task_task_item_path(@task, task_item), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-delete'

app/views/task_items/new.html.haml
= render 'form', task_item: @task_item

app/views/task_items/show.html.haml
%p#notice= notice
%p
  %strong Title:
  = @task_item.title
%p
  %strong Body:
  = @task_item.body
%p
  %strong Due days:
  = @task_item.due_days
= link_to 'Edit', edit_task_task_item_path(@task_item)
|
= link_to 'Back', task_task_items_path

app/views/tasks/_form.html.haml
#todo.py-5
  .container
    .img-content-wrapper
      %img.img-fluid.rounded{:alt => "", :src => "#{asset_path('img-holder.png')}"}/
      %h4.dashboard-title
        %a{:href => "#"} Add Todos
    #add-todo
      = form_with(model: task) do |form|
        - if task.errors.any?
          #error_explanation
            %h2
              = pluralize(task.errors.count, "error")
              prohibited this task from being saved:
            %ul
              - task.errors.each do |error|
                %li= error.full_message
        .form-group
          = form.text_field :task_name, class:'form-control', placeholder: 'Enter Task Name'
        #action-buttons.text-center.mt-4
          = link_to 'CANCEL', tasks_path, class: 'btn  btn-edit btn-general'
          = form.submit class: 'btn  btn-edit btn-general'

app/views/tasks/edit.html.haml
%h1 Editing Task
= render 'form', task: @task
= link_to 'Back', tasks_path

app/views/tasks/index.html.haml
%p#notice= notice
%div{:id => "dashboard task-dashboard"}
  .container
    .row.mb-4
      .col-md-10
        %h2 Tasks
      .col-md-2.text-right
        = link_to 'Add Task',new_task_path, class: 'btn btn-success text-white ml-1'

    #todo-wrapper
      - @tasks.each do |task|
        .row.mb-1.data-row
          .col-md-6.ml-1
            = task.task_name
          .col-md-3.ml-1
            = task.created_at.strftime("%e %b, %Y")
          .col-md-3.text-right
            = link_to 'Items', task_task_items_path(task), class: 'btn btn-primary', role: :button
            = link_to 'Edit', edit_task_path(task), class: 'btn btn-primary btn-edit', role: :button
            = link_to 'Archive', task, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-delete'

app/views/tasks/new.html.haml
= render 'form', task: @task